spring:
  cloud:
    stream:
      bindings:
        process-in-0:
          destination: sensor-topic
          consumer:
            useNativeDecoding: true
      kafka:

#        binder:
#          consumerProperties:
#            value:
#              subject:
#                name:
#                  strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy

        bindings:
          process-in-0:
            consumer:
              configuration:
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                schema.registry.url: http://localhost:8081
                specific.avro.reader: true

server.port: 9999
